import{a as L,S as b,i}from"./assets/vendor-D8_O3--j.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const w="https://pixabay.com/api/",v="50980085-22439fb0ce1b09a2c0941d25f",E=15;async function u(n,e=1){const s={key:v,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:E};return(await L.get(w,{params:s})).data}function m(n){const e=document.querySelector(".gallery"),s=n.map(o=>`
      <a href="${o.largeImageURL}" class="gallery-item">
        <img src="${o.webformatURL}" alt="${o.tags}" />
        <div class="info">
          <p><b>Likes:</b> ${o.likes}</p>
          <p><b>Views:</b> ${o.views}</p>
          <p><b>Comments:</b> ${o.comments}</p>
          <p><b>Downloads:</b> ${o.downloads}</p>
        </div>
      </a>
    `).join("");e.insertAdjacentHTML("beforeend",s)}function S(){document.querySelector(".gallery").innerHTML=""}function h(){document.getElementById("load-more").classList.remove("hidden")}function f(){document.getElementById("load-more").classList.add("hidden")}const R=document.querySelector("form"),q=document.querySelector('input[name="search"]'),B=document.getElementById("load-more"),I=document.querySelector(".gallery"),p=document.getElementById("search-loader"),g=document.getElementById("loadmore-loader");function M(){p.classList.remove("hidden")}function P(){p.classList.add("hidden")}function $(){g.classList.remove("hidden")}function O(){g.classList.add("hidden")}let c="",a=1,d=0;const y=new b(".gallery a");R.addEventListener("submit",async n=>{if(n.preventDefault(),c=q.value.trim(),!c){i.warning({message:"Please enter a search term.",position:"topRight"});return}S(),f(),a=1;try{M();const e=await u(c,a);if(d=e.totalHits,e.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(e.hits),y.refresh(),d>a*15&&h()}catch{i.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{P()}});B.addEventListener("click",async()=>{var n;a+=1,$(),f();try{const e=await u(c,a);m(e.hits),y.refresh();const s=((n=I.firstElementChild)==null?void 0:n.getBoundingClientRect().height)||0;window.scrollBy({top:s*2,behavior:"smooth"}),a*15>=d?i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):h()}catch{i.error({message:"Failed to load more images.",position:"topRight"})}finally{O()}});
//# sourceMappingURL=index.js.map
